{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_alluredemo1.py:10: AssertionError"}, "description": "this test fails", "start": 1603938322865, "stop": 1603938322866, "uuid": "0205dfcd-1cb6-4009-bfee-01f2b283e10d", "historyId": "9e8d23832460ad3c87806390b91ae72c", "testCaseId": "d3ba699b3e70ee73490c0d009b152181", "fullName": "test_alluredemo1#test_failure", "labels": [{"name": "suite", "value": "test_alluredemo1"}, {"name": "host", "value": "nb2-hz20113336"}, {"name": "thread", "value": "5184-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo1"}]}